### ISSUE TITLE
github PR templates aren't working

### ISSUE THREAD

**Issue by antifuchs** [antifuchs/o#13]
I think I made the [pull request templates](https://github.com/antifuchs/o/tree/master/.github/PULL_REQUEST_TEMPLATE) wrong: A new PR doesn't offer any "kind" of pull request, and the form is blank.

I *thought* I'd done it according to https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository, but maybe not.

**Comment by wireguy** [comment]
@antifuchs , I think you would need to specify the name of the template, as in ?template=

Otherwise github is looking for the default template name of PULL_REQUEST_TEMPLATE.md
and since you don't have that file, it shows blank.

See: [github blog entry about mutiple templates](https://github.blog/2018-01-25-multiple-issue-and-pull-request-templates/)

**Comment by antifuchs** [comment]
Ooooh, that makes sense (feels pretty weird from a github UX perspective, but then I haven't seen this work before). I'll make a single template, then. Thanks!

**Comment by antifuchs** [comment]
Aaaand the single template introduced in ecc8ce016425aebfefa4c247511cdd083d6263d1 works. Thanks again for the help & confirmation!
